### ISSUE TITLE
Observable-Sharing dramatically increases solver run-time when sharing few expressions

### ISSUE THREAD

**Issue by bruderj15** [bruderj15/Hasmtlib#97]
The sharing obviously yields big benefits for instances where we actually share a lot.
However, for all my instances where there is barely gain from sharing, solver-runtime dramatically increases.
My use-cases in general do not offer a lot of sharing, I guess equally for the average user.

Also to note that big instances - with sharing enabled - often lead to the solver crashing (memory - too many vars).

Therefore default `SharingMode` to `None` .

**Comment by fabeulous** [comment]
I observed the same performance decrease where sharing is not used a lot. In applications where sharing leads to significantly smaller formulas, I unsurprisingly do see better results. However,  this is likely not the common case and I would agree that disabling sharing by default is the way to go.

I usually know which sub-formulas should be shared for a given encoding. The main benefit I got from the observable sharing approach was simplicity. Especially in combination with the "constant folding", I don't have to worry if my shared subformula could be eliminated since the sharing only happens after formula construction.

**Comment by jwaldmann** [comment]
Wat. I _do_ want sharing (#126)  For all sub-formulas. Example code: https://github.com/jwaldmann/Hasmtlib/blob/develop/src/Language/Hasmtlib/Example/NIA.hs  Needs shared arithmetical sub-expressions, and will blow up terribly without, for larger matrix dimensions. 

The NIA solvers won't help for interesting termination problems, but the same idea applies for other variants, in particular, I am interested in BV, since SMTLIB added overflow predicates.

If it is really the case that a solver cannot handle these extra variables bound by equalities, but can handle the unfolded version, then I consider this a bug in in the solver that should be reported. Better yet, such formulas should be submitted to next STMcomp. (I'm not saying that you should do it. It would make a nice (bachelor) student project.)
